version: "3"
services:
  react-app:
    image: flower:latest
    ports:
      - 80:80
    volumes:
      - ./:/usr/share/nginx/html
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - is332-app
networks:
  is332-app:
    external: true
#to create network
# docker network create --driver=overlay is332-app
 